### ISSUE TITLE
how to multiple domains? (localhost, IP, domain)

### ISSUE THREAD

**Issue by saul-salazar-dotcom** [will-moss/erin#13]
Hi,

Is is possible to have multiple domains? for example I want to be able to access erin in 3 ways:
- with my local IP (192.168.100.10)
- with `localhost`
- with a custom domain (`tiktok.homelab.com`)

but it seems like I only can choose one

Right now I want another people to access erin in my local network, so I had to set the env var `PUBLIC_URL` to `http://192.168.100.10:3333` but now I cannot access via `localhost:3333`

But I want to access via `tiktok.homelab.com` but only on my LAN, so I added traefik proxy to help with that but it doesnt work :(

I have 10 applications via docker compose and I expose them via Traefik and a local https certificate (thanks to [mkcert.dev](https://mkcert.dev/)), I only add a few labels and it works OK on all applications except erin, this is my current `docker-compose.yaml` file

```yaml
name: tiktok

networks:
  proxy:
    external: true

services:
  erin:
    image: mosswill/erin:latest
    ports:
      - "3333:3333"
    volumes:
      - "/e/videos/:/srv/videos:ro"
    networks:
      - proxy
    environment:
      PUBLIC_URL: "http://192.168.100.10:3333"
      AUTH_ENABLED: "false"
      AUTOPLAY_ENABLED: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`tiktok.homelab.com`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3333"
```
